# Generated by Django 4.2.1 on 2023-07-31 08:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0009_googleurl'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='user_photo',
            field=models.ImageField(blank=True, null=True, upload_to='', verbose_name='User Photo'),
        ),
        migrations.AddField(
            model_name='historicalcustomuser',
            name='user_photo',
            field=models.TextField(blank=True, max_length=100, null=True, verbose_name='User Photo'),
        ),
    ]
