# Generated by Django 4.2.1 on 2023-08-01 11:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0010_customuser_user_photo_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='user_photo',
            field=models.ImageField(blank=True, default='user_place_holder.jpg', null=True, upload_to='', verbose_name='User Photo'),
        ),
        migrations.AlterField(
            model_name='historicalcustomuser',
            name='user_photo',
            field=models.TextField(blank=True, default='user_place_holder.jpg', max_length=100, null=True, verbose_name='User Photo'),
        ),
    ]
