# Generated by Django 4.2.1 on 2023-08-01 11:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('albuns', '0009_historicalalbum'),
    ]

    operations = [
        migrations.AddField(
            model_name='album',
            name='public',
            field=models.BooleanField(default='False', verbose_name='Publico'),
        ),
        migrations.AddField(
            model_name='historicalalbum',
            name='public',
            field=models.BooleanField(default='False', verbose_name='Publico'),
        ),
    ]
