# Generated by Django 4.2.1 on 2023-08-01 11:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('albuns', '0010_album_public_historicalalbum_public'),
    ]

    operations = [
        migrations.AlterField(
            model_name='album',
            name='public',
            field=models.BooleanField(default='True', verbose_name='Publico'),
        ),
        migrations.AlterField(
            model_name='historicalalbum',
            name='public',
            field=models.BooleanField(default='True', verbose_name='Publico'),
        ),
    ]
